services:
  - type: web
    name: paper-recommender-api
    runtime: python
    buildCommand: pip install -r requirements_api.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0